### PR TITLE
Fix source for the demo

### LINKED ISSUE #22: Fix gh-pages demo
The manifest used on the demo page references pawpaw.dlib.indiana.edu which has been decommissioned.  This could be changed to reference demo.avalonmediasystem.org or to a sample manifest from a IIIF github organization source.

### PR DESCRIPTION
**Pull request by Dananji**
Closes #22

### CODE REVIEW

File: demo/src/index.js [hunk 1]
```diff
@@ -8,7 +8,7 @@ import iiifManifest from '../../src/json/manifest-pawpaw-mahler';
 
 // A valid IIIF Manifest URI endpoint
 const iiifManifestUrl =
-  'https://pawpaw.dlib.indiana.edu/media_objects/2j62s484w/manifest.json';
+  'http://dlib.indiana.edu/iiif_av/mahler-symphony-3/mahler-symphony-3.json';
```
Comment (phuongdh) [inline demo/src/index.js]: Chrome has started prohibiting mixed content requests so this might not work if it's used in a https website. I'd change it to https to avoid potential problems.

File: dist/services/iiif-parser.js [hunk 2]
```diff
@@ -118,13 +118,13 @@ function getChoiceItems(manifest) {
 function getLabelValue(label) {
   if (label && (0, _typeof2["default"])(label) === 'object') {
     // English
-    if (label.hasOwnProperty('@en')) {
-      return label['@en'].length > 0 ? label['@en'][0] : '';
+    if (label.hasOwnProperty('en')) {
```
Comment (phuongdh) [inline dist/services/iiif-parser.js]: Can you explain the change from @ to non-@?

Comment (Dananji) [reply dist/services/iiif-parser.js]: Yes it's a iiif spec change.

File: dist/services/iiif-parser.js [hunk 3]
```diff
@@ -118,13 +118,13 @@ function getChoiceItems(manifest) {
...
+      return label['en'].length > 0 ? label['en'][0] : '';
     } // None
 
 
-    if (label.hasOwnProperty('@none')) {
-      return label['@none'].length > 0 ? label['@none'][0] : '';
+    if (label.hasOwnProperty('none')) {
+      return label['none'].length > 0 ? label['none'][0] : '';
```
Comment (cjcolvar) [inline dist/services/iiif-parser.js]: :+1: I didn't know the `@` was dropped for `none` as well but I see it in the specs.  Good catch!
